# Generated by Django 6.0.2 on 2026-04-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.CharField(default='0h om', max_length=20),
        ),
    ]
